apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.springboot.service.name }}
spec:
  type: {{ .Values.springboot.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.springboot.image.port }}
  selector:
    server: {{ .Values.springboot.name }}